name: fighter_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.15.0   # ✅ adicionado para Firestore

  # Ícones e utilitários
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4
  path_provider: ^2.1.2
  http: ^1.4.0   # atualizado para versão compatível com flutterfire_cli
  rename_app: ^1.6.5
  flutter_vector_icons: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutterfire_cli: ^1.3.1
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/fighter_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/fighter_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/fighter_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/fighter_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/boxing.png
    - assets/fighter_bg.png
    - assets/pfp.jpg
    - assets/ana.jpg
    - assets/carlos.jpg
    - assets/marina.jpg
    - assets/usuario.jpg
