// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo_8RqAkfZt113fQdTYfFFhJJZkSeObK0',
    appId: '1:68148951625:web:91e8d1c3590daea7fbdd98',
    messagingSenderId: '68148951625',
    projectId: 'fighters-f93c0',
    authDomain: 'fighters-f93c0.firebaseapp.com',
    databaseURL: 'https://fighters-f93c0-default-rtdb.firebaseio.com',
    storageBucket: 'fighters-f93c0.firebasestorage.app',
    measurementId: 'G-NKPZNX67QH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtHFI2Ipm1fpXE8NKgelJf-kqfy3o3zl0',
    appId: '1:68148951625:android:a89311d9dbef1871fbdd98',
    messagingSenderId: '68148951625',
    projectId: 'fighters-f93c0',
    databaseURL: 'https://fighters-f93c0-default-rtdb.firebaseio.com',
    storageBucket: 'fighters-f93c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPOqSmNuMwRNAjfbv-LJID-VF2BYMRctk',
    appId: '1:68148951625:ios:d3d21d0d0b2f9561fbdd98',
    messagingSenderId: '68148951625',
    projectId: 'fighters-f93c0',
    databaseURL: 'https://fighters-f93c0-default-rtdb.firebaseio.com',
    storageBucket: 'fighters-f93c0.firebasestorage.app',
    iosBundleId: 'com.example.fighterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPOqSmNuMwRNAjfbv-LJID-VF2BYMRctk',
    appId: '1:68148951625:ios:d3d21d0d0b2f9561fbdd98',
    messagingSenderId: '68148951625',
    projectId: 'fighters-f93c0',
    databaseURL: 'https://fighters-f93c0-default-rtdb.firebaseio.com',
    storageBucket: 'fighters-f93c0.firebasestorage.app',
    iosBundleId: 'com.example.fighterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo_8RqAkfZt113fQdTYfFFhJJZkSeObK0',
    appId: '1:68148951625:web:056757d5801b44f5fbdd98',
    messagingSenderId: '68148951625',
    projectId: 'fighters-f93c0',
    authDomain: 'fighters-f93c0.firebaseapp.com',
    databaseURL: 'https://fighters-f93c0-default-rtdb.firebaseio.com',
    storageBucket: 'fighters-f93c0.firebasestorage.app',
    measurementId: 'G-28NQGKCRHN',
  );
}
